// Generated by CoffeeScript 1.6.2
var ShapeFile, shapeFile;

ShapeFile = require('./build/Release/shapelib_bindings').ShapeFile;

shapeFile = new ShapeFile();

shapeFile.open('./deps/huh/ne_110m_land', function(err, shapeData) {
  console.log({
    open: {
      error: err,
      data: shapeData
    }
  });
  return console.log(shapeData.shapes);
});
